feat: Forgot to save some shit

diff --git a/home/dot_shellfn b/home/dot_shellfn
--- a/home/dot_shellfn
+++ b/home/dot_shellfn
@@ -1,1 +1,218 @@
-/Users/gehrigkeane/.dotfiles/homedir/.shellfn
+#########################################
+# Utility Functions
+#########################################
+
+function update() {
+  # brew
+  printf "${INFO}Updating brew\n${NORMAL}"
+  brew update
+  brew upgrade
+  brew upgrade --cask
+  brew cleanup --prune all -s
+  brew doctor --verbose
+
+  # mise
+  printf "${INFO}Updating mise\n${NORMAL}"
+  mise self-update
+  mise plugins upgrade
+  mise upgrade --bump
+
+  # zinit
+  printf "${INFO}Updating zinit\n${NORMAL}"
+  zinit update --all
+
+  # tldr
+  printf "${INFO}Updating tldr\n${NORMAL}"
+  tldr --update
+
+  # macOS
+  printf "${WARN}Update macOS? [y|N] ${NORMAL}"
+  read -r response
+  if [[ $response =~ (y|yes|Y) ]]; then
+    printf "${INFO}Updating macOS\n${NORMAL}"
+    sudo softwareupdate -i -a;
+  fi
+}
+
+#
+# AWS
+
+# ref: https://github.com/aws/amazon-ssm-agent/issues/131
+# TODO: https://aws.amazon.com/blogs/mt/bring-your-own-cli-session-manager-configurable-shell-profiles/
+function awssm() {
+  aws ssm start-session \
+    --document-name AWS-StartInteractiveCommand \
+    --parameters '{"command": ["sudo --login ; PS1=\"\\t [\\u@\\h \\w]> \" PROMPT_DIRTRIM=2 bash"]}' \
+    --target "$@"
+}
+
+function awsso() {
+  printf "${GREEN}SSOing\n${NORMAL}"
+  aws sso login
+  printf "${GREEN}SSO Complete, yawsso'ing\n${NORMAL}"
+  yawsso
+}
+
+function memusage() {
+  ps -eo size,command --sort -size | grep $1 | awk '{ hr=$1/1024 ; sum +=hr} END {print sum"MiB"}'
+}
+
+#
+# Util
+function killport() {
+  PORT="${1:-8080}"
+  procs=$(lsof -iTCP -sTCP:LISTEN -n -P | rg "$PORT")
+
+  if [ -z "$procs" ]; then
+    printf "${RED}no process found for port=$PORT\n${NORMAL}"
+    return 1
+  fi
+
+  pid=$(printf "$procs" | cut -w -f2)
+  printf "${GREEN}Killing pid=$pid\n>\t$procs\n${NORMAL}"
+  kill "$pid"
+}
+
+#
+#
+
+function bot() {
+  ESC_SEQ="\x1b["
+  echo
+  echo -e "$ESC_SEQ"32;01m\[._.]/$ESC_SEQ"39;49;00m - "$1
+}
+
+## get the timings for a curl to a URL
+## usage: curltime $url
+function curltime(){
+  curl -w "   time_namelookup:  %{time_namelookup}\n\
+      time_connect:  %{time_connect}\n\
+   time_appconnect:  %{time_appconnect}\n\
+  time_pretransfer:  %{time_pretransfer}\n\
+     time_redirect:  %{time_redirect}\n\
+time_starttransfer:  %{time_starttransfer}\n\
+--------------------------\n\
+        time_total:  %{time_total}\n" -o /dev/null -s "$1"
+}
+
+## output directory/file tree, excluding ignorables
+function tre(){
+  tree -aC -I '.git|node_modules|bower_components|.DS_Store' --dirsfirst "$@"
+}
+
+## weather seattle
+function weather() {
+  curl wttr.in/$1
+}
+
+function fix_trailing_newline() {
+  GREEN=$(tput setaf 2)
+  NORMAL=$(tput sgr0)
+
+  for file in "$@"
+  do
+    printf "${GREEN}Fixing trailing newline for %s\n${NORMAL}" "$file" >&2
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+      sed -i '' -e '$a\' "$1"
+    else
+      sed -i -e '$a\' "$1"
+    fi
+  done
+}
+alias fta=fix_trailing_newline
+
+#########################################
+# Unused
+#########################################
+
+# Create a new git repo with one README commit and CD into it
+# function gitnr() { mkdir $1; cd $1; git init; touch README; git add README; git commit -mFirst-commit;}
+
+# Do a Matrix movie effect of falling characters
+# function matrix1() {
+# echo -e "\e[1;40m" ; clear ; while :; do echo $LINES $COLUMNS $(( $RANDOM % $COLUMNS)) $(( $RANDOM % 72 )) ;sleep 0.05; done|gawk '{ letters="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*()"; c=$4; letter=substr(letters,c,1);a[$3]=0;for (x in a) {o=a[x];a[x]=a[x]+1; printf "\033[%s;%sH\033[2;32m%s",o,x,letter; printf "\033[%s;%sH\033[1;37m%s\033[0;0H",a[x],x,letter;if (a[x] >= $1) { a[x]=0; } }}'
+# }
+
+# function matrix2() {
+# echo -e "\e[1;40m" ; clear ; characters=$( jot -c 94 33 | tr -d '\n' ) ; while :; do echo $LINES $COLUMNS $(( $RANDOM % $COLUMNS)) $(( $RANDOM % 72 )) $characters ;sleep 0.05; done|gawk '{ letters=$5; c=$4; letter=substr(letters,c,1);a[$3]=0;for (x in a) {o=a[x];a[x]=a[x]+1; printf "\033[%s;%sH\033[2;32m%s",o,x,letter; printf "\033[%s;%sH\033[1;37m%s\033[0;0H",a[x],x,letter;if (a[x] >= $1) { a[x]=0; } }}'
+# }
+
+# Use Mac OS Preview to open a man page in a more handsome format
+# function manp() {
+#   man -t $1 | open -f -a /Applications/Preview.app
+# }
+
+# Show normally hidden system and dotfile types of files
+# in Mac OS Finder
+# function showhiddenfiles() {
+#   defaults write com.apple.Finder AppleShowAllFiles YES
+#   osascript -e 'tell application "Finder" to quit'
+#   sleep 0.25
+#   osascript -e 'tell application "Finder" to activate'
+# }
+
+# Hide (back to defaults) normally hidden system and dotfile types of files
+# in Mac OS Finder
+# function hidehiddenfiles() {
+#   defaults write com.apple.Finder AppleShowAllFiles NO
+#   osascript -e 'tell application "Finder" to quit'
+#   sleep 0.25
+#   osascript -e 'tell application "Finder" to activate'
+# }
+
+## hammer a service with curl for a given number of times
+## usage: curlhammer $url
+# function curlhammer () {
+#   bot "about to hammer $1 with $2 curls ⇒";
+#   echo "curl -k -s -D - $1 -o /dev/null | grep 'HTTP/1.1' | sed 's/HTTP\/1.1 //'"
+#   for i in {1..$2}
+#   do
+#     curl -k -s -D - $1 -o /dev/null | grep 'HTTP/1.1' | sed 's/HTTP\/1.1 //'
+#   done
+#   bot "done"
+# }
+
+## curlheader will return only a specific response header or all response headers for a given URL
+## usage: curlheader $header $url
+## usage: curlheader $url
+# function curlheader() {
+#   if [[ -z "$2" ]]; then
+#     echo "curl -k -s -D - $1 -o /dev/null"
+#     curl -k -s -D - $1 -o /dev/null:
+#   else
+#     echo "curl -k -s -D - $2 -o /dev/null | grep $1:"
+#     curl -k -s -D - $2 -o /dev/null | grep $1:
+#   fi
+# }
+
+# function fixperms(){
+#     find . \( -name "*.sh" -or -type d \) -exec chmod 755 {} \; && find . -type f ! -name "*.sh" -exec chmod 644 {} \;
+# }
+
+# Create a new directory and enter it
+# function mkd() {
+#   mkdir -p "$@" && cd "$_";
+# }
+
+# Generate Subresource Integrity hashes.
+# 1st argument is the filename.
+# 2nd argument, optional, is the hash algorithm
+# (currently the allowed prefixes are sha256, sha384, and sha512)
+# See http://www.w3.org/TR/SRI/ and
+# https://developer.mozilla.org/docs/Web/Security/Subresource_Integrity
+# function sri() {
+#   if [ -z "${1}" ]; then
+#     echo "ERROR: No file specified.";
+#     return 1;
+#   fi;
+#   local algorithm="${2:-sha512}"
+#   if ! echo "${algorithm}" | egrep -q "^sha(256|384|512)$"; then
+#     echo "ERROR: hash algorithm must be sha256, sha384 or sha512.";
+#     return 1;
+#   fi;
+#   local filehash=$(openssl dgst "-${algorithm}" -binary "$1" | openssl base64 -A)
+#   if [ -z "${filehash}" ]; then
+#     return 1;
+#   fi;
+#   echo "${algorithm}-${filehash}";
+# }
